### ISSUE TITLE
type range error

### ISSUE THREAD

**Issue by poltpolt** [FlorianRaediker/world2minetest#4]
I am not familiar with python but i get an error
- here is my xyz file https://cloud.inicio.pl/index.php/s/aZFaqoAKmkmAgLe

and here is the command with its result

python3 parse_heightmap_xyz.py ../rincon50m.xyz 
rincon50m.xyz
min: (-479502, 4398604) height: 24
max: (-469602, 4406004) height: 255
size: (9901, 7401)
0
0
Traceback (most recent call last):
  File "/home/mintest/world2minetest/parse_heightmap_xyz.py", line 48, in <module>
    out.write(to_bytes(min_x, 4))
  File "/home/mintest/world2minetest/_util.py", line 5, in to_bytes
    x = [None, np.uint8, np.uint16, None, np.uint32][length](x)
OverflowError: Python integer -479502 out of bounds for uint32

**Comment by poltpolt** [comment]
I was able to engage AI to fix the errors but the heightmap is basically 0
when i generated world with it it was plain as table

here are the changes done to stop the errors, @fyrk  are you able to see if it makes sense?:
https://pastebin.com/xiWGMGNL
